# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aSolid_app', '0004_auto_20180628_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
    ]
