# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aSolid_app', '0005_remove_user_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='add',
            field=models.ManyToManyField(related_name='add', to='aSolid_app.Quote'),
        ),
    ]
