# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aSolid_app', '0006_auto_20180628_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='poster',
        ),
        migrations.AlterField(
            model_name='user',
            name='add',
            field=models.ManyToManyField(related_name='add', to='aSolid_app.Job'),
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.AddField(
            model_name='job',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_jobs', to='aSolid_app.User'),
        ),
    ]
