# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aSolid_app', '0007_auto_20180628_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='author',
            new_name='job',
        ),
        migrations.AlterField(
            model_name='job',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_jobs', to='aSolid_app.User'),
        ),
    ]
