# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aSolid_app', '0008_auto_20180628_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='content',
            new_name='description',
        ),
    ]
